#
# Makefile for shrek6410 board
#

obj-$(CONFIG_DRV01) += char_test01.o
obj-$(CONFIG_DRV02) += char_test02.o
obj-$(CONFIG_LED01) += led_test02.o
obj-$(CONFIG_KEY01) += key_test02.o
obj-$(CONFIG_TIMER01) += timer_test02.o
obj-$(CONFIG_ATOM01) += atomic_test01.o
obj-$(CONFIG_SPIN01) += spin_test01.o

